package edu.pe.unsch.entities;
// Generated 02/06/2019 02:58:27 AM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Categoria generated by hbm2java
 */
@Entity
@Table(name = "categoria", catalog = "db_ecommerce", uniqueConstraints = @UniqueConstraint(columnNames = "categoria"))
public class Categoria implements java.io.Serializable {

	private Integer id;
	private Categoria categoria;
	private String categoria_1;
	private Boolean visible;
	private Set<Productos> productoses = new HashSet<Productos>(0);
	private Set<Categoria> categorias = new HashSet<Categoria>(0);

	public Categoria() {
	}

	public Categoria(Categoria categoria, String categoria_1, Boolean visible, Set<Productos> productoses,
			Set<Categoria> categorias) {
		this.categoria = categoria;
		this.categoria_1 = categoria_1;
		this.visible = visible;
		this.productoses = productoses;
		this.categorias = categorias;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "categoria_superior_id")
	public Categoria getCategoria() {
		return this.categoria;
	}

	public void setCategoria(Categoria categoria) {
		this.categoria = categoria;
	}

	@Column(name = "categoria", unique = true, length = 60)
	public String getCategoria_1() {
		return this.categoria_1;
	}

	public void setCategoria_1(String categoria_1) {
		this.categoria_1 = categoria_1;
	}

	@Column(name = "visible")
	public Boolean getVisible() {
		return this.visible;
	}

	public void setVisible(Boolean visible) {
		this.visible = visible;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categoria")
	public Set<Productos> getProductoses() {
		return this.productoses;
	}

	public void setProductoses(Set<Productos> productoses) {
		this.productoses = productoses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categoria")
	public Set<Categoria> getCategorias() {
		return this.categorias;
	}

	public void setCategorias(Set<Categoria> categorias) {
		this.categorias = categorias;
	}

}
