package edu.pe.unsch.entities;
// Generated 22/07/2019 10:23:08 PM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Distrito generated by hbm2java
 */
@Entity
@Table(name = "distrito", catalog = "ecommerceremate")
public class Distrito implements java.io.Serializable {

	private Integer id;
	private Provincia provincia;
	private String denominacion;
	private String ubigeo;
	private Set<Cliente> clientes = new HashSet<Cliente>(0);

	public Distrito() {
	}

	public Distrito(Provincia provincia, String denominacion, String ubigeo, Set<Cliente> clientes) {
		this.provincia = provincia;
		this.denominacion = denominacion;
		this.ubigeo = ubigeo;
		this.clientes = clientes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "provincia_id")
	public Provincia getProvincia() {
		return this.provincia;
	}

	public void setProvincia(Provincia provincia) {
		this.provincia = provincia;
	}

	@Column(name = "denominacion", length = 60)
	public String getDenominacion() {
		return this.denominacion;
	}

	public void setDenominacion(String denominacion) {
		this.denominacion = denominacion;
	}

	@Column(name = "ubigeo", length = 20)
	public String getUbigeo() {
		return this.ubigeo;
	}

	public void setUbigeo(String ubigeo) {
		this.ubigeo = ubigeo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "distrito")
	public Set<Cliente> getClientes() {
		return this.clientes;
	}

	public void setClientes(Set<Cliente> clientes) {
		this.clientes = clientes;
	}

}
