package edu.pe.unsch.entities;
// Generated 02/06/2019 02:58:27 AM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Marca generated by hbm2java
 */
@Entity
@Table(name = "marca", catalog = "db_ecommerce", uniqueConstraints = @UniqueConstraint(columnNames = "nombre"))
public class Marca implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private Boolean visible;
	private Set<Productos> productoses = new HashSet<Productos>(0);

	public Marca() {
	}

	public Marca(String nombre, Boolean visible, Set<Productos> productoses) {
		this.nombre = nombre;
		this.visible = visible;
		this.productoses = productoses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nombre", unique = true, length = 40)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "visible")
	public Boolean getVisible() {
		return this.visible;
	}

	public void setVisible(Boolean visible) {
		this.visible = visible;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "marca")
	public Set<Productos> getProductoses() {
		return this.productoses;
	}

	public void setProductoses(Set<Productos> productoses) {
		this.productoses = productoses;
	}

}
