package edu.pe.unsch.entities;
// Generated 22/07/2019 10:23:08 PM by Hibernate Tools 5.1.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Orden generated by hbm2java
 */
@Entity
@Table(name = "orden", catalog = "ecommerceremate")
public class Orden implements java.io.Serializable {

	private Integer id;
	private Login login;
	private String nombre;
	private Date fechacreacion;
	private Byte estado;
	private Set<Detalleorden> detalleordens = new HashSet<Detalleorden>(0);

	public Orden() {
	}

	public Orden(Login login, String nombre, Date fechacreacion, Byte estado, Set<Detalleorden> detalleordens) {
		this.login = login;
		this.nombre = nombre;
		this.fechacreacion = fechacreacion;
		this.estado = estado;
		this.detalleordens = detalleordens;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idlogin")
	public Login getLogin() {
		return this.login;
	}

	public void setLogin(Login login) {
		this.login = login;
	}

	@Column(name = "nombre", length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechacreacion", length = 10)
	public Date getFechacreacion() {
		return this.fechacreacion;
	}

	public void setFechacreacion(Date fechacreacion) {
		this.fechacreacion = fechacreacion;
	}

	@Column(name = "estado")
	public Byte getEstado() {
		return this.estado;
	}

	public void setEstado(Byte estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orden")
	public Set<Detalleorden> getDetalleordens() {
		return this.detalleordens;
	}

	public void setDetalleordens(Set<Detalleorden> detalleordens) {
		this.detalleordens = detalleordens;
	}

}
