package edu.pe.unsch.entities;
// Generated 22/07/2019 10:23:08 PM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Region generated by hbm2java
 */
@Entity
@Table(name = "region", catalog = "ecommerceremate")
public class Region implements java.io.Serializable {

	private Integer id;
	private String denominacion;
	private String ubigeo;
	private Set<Provincia> provincias = new HashSet<Provincia>(0);

	public Region() {
	}

	public Region(String denominacion, String ubigeo, Set<Provincia> provincias) {
		this.denominacion = denominacion;
		this.ubigeo = ubigeo;
		this.provincias = provincias;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "denominacion", length = 60)
	public String getDenominacion() {
		return this.denominacion;
	}

	public void setDenominacion(String denominacion) {
		this.denominacion = denominacion;
	}

	@Column(name = "ubigeo", length = 4)
	public String getUbigeo() {
		return this.ubigeo;
	}

	public void setUbigeo(String ubigeo) {
		this.ubigeo = ubigeo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "region")
	public Set<Provincia> getProvincias() {
		return this.provincias;
	}

	public void setProvincias(Set<Provincia> provincias) {
		this.provincias = provincias;
	}

}
